// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EmprestimoDeLivros.API.Models;

[Table("Livro_Cliente_Emprestimo")]
public partial class LivroClienteEmprestimo
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    public int LecIdLivro { get; set; }

    public int LecIdCliente { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime LecDataEmprestimo { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime LecDataEntrega { get; set; }

    public bool LecDataEntregue { get; set; }

    [ForeignKey("LecIdCliente")]
    [InverseProperty("LivroClienteEmprestimo")]
    public virtual Cliente LecIdClienteNavigation { get; set; }

    [ForeignKey("LecIdLivro")]
    [InverseProperty("LivroClienteEmprestimo")]
    public virtual Livro LecIdLivroNavigation { get; set; }
}